title: My Static Site
description: A Jekyll site with a single-page structure and blog.
# _config.yml
url: "https://benedictsaunders.github.io"
baseurl: "/benedictsaunders.github.io"

# Force posts to render at /articles/title.html
permalink: /articles/:title.html

# Exclude development files from the build output
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

collections:
  sections:
    output: false

contact:
  github: "github.com/benedictsaunders"
  linkedin: "linkedin.com/in/benedictsaunders"